### ISSUE TITLE
panic: nil pointer dereference 

### ISSUE THREAD

**Issue by thorfour** [rdleal/intervalst#3]
We recently hit the panic below. Not that this is on a tree that only performs `Insert` and `AllIntersections` calls, no deletes.

Looks like https://github.com/rdleal/intervalst/blob/fee6a243498510e53cd8a397b4aaafcf1757495d/interval/node.go#L107
means that the nodes left value is nil.  

I'm wondering if this is because the `MultiValueSearchTree` does not use the mutex that the SearchTree does and our code performs concurrent inserts. Is this a bug or is the `MultiValueSearchTree` intended to not be thread safe?
https://github.com/rdleal/intervalst/blob/fee6a243498510e53cd8a397b4aaafcf1757495d/interval/insert.go#L75-L81
https://github.com/rdleal/intervalst/blob/fee6a243498510e53cd8a397b4aaafcf1757495d/interval/insert.go#L12-L21

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xd465f9]

goroutine 91615 [running]:
github.com/rdleal/intervalst/interval.rotateRight[...](0x0?, 0x18b4a34b0ea?)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/node.go:107 +0x19
github.com/rdleal/intervalst/interval.balanceNode[...](0x18b4a8b9bab?, 0x120000fd?)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/node.go:125 +0x99
github.com/rdleal/intervalst/interval.upsert[...](0xc591da0500, {{0x0, 0x18b4a2935c8, 0xfd, 0x0, 0x0, 0x0}, {0x0, 0x18b4a34b0ea, 0xfd, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/insert.go:53 +0x4d0
github.com/rdleal/intervalst/interval.upsert[...](0xc52c780aa0, {{0x0, 0x18b4a2935c8, 0xfd, 0x0, 0x0, 0x0}, {0x0, 0x18b4a34b0ea, 0xfd, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/insert.go:44 +0x345
github.com/rdleal/intervalst/interval.upsert[...](0xc56f4e4dc0, {{0x0, 0x18b4a2935c8, 0xfd, 0x0, 0x0, 0x0}, {0x0, 0x18b4a34b0ea, 0xfd, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/insert.go:44 +0x345
github.com/rdleal/intervalst/interval.upsert[...](0xc54b665d60, {{0x0, 0x18b4a2935c8, 0xfd, 0x0, 0x0, 0x0}, {0x0, 0x18b4a34b0ea, 0xfd, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/insert.go:44 +0x345
github.com/rdleal/intervalst/interval.upsert[...](0xc520cffa40, {{0x0, 0x18b4a2935c8, 0xfd, 0x0, 0x0, 0x0}, {0x0, 0x18b4a34b0ea, 0xfd, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/insert.go:44 +0x345
github.com/rdleal/intervalst/interval.upsert[...](0xc4d3f259a0, {{0x0, 0x18b4a2935c8, 0xfd, 0x0, 0x0, 0x0}, {0x0, 0x18b4a34b0ea, 0xfd, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/insert.go:44 +0x345
github.com/rdleal/intervalst/interval.upsert[...](0xc45c0bfe00, {{0x0, 0x18b4a2935c8, 0xfd, 0x0, 0x0, 0x0}, {0x0, 0x18b4a34b0ea, 0xfd, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/insert.go:44 +0x345
github.com/rdleal/intervalst/interval.upsert[...](0xc430d206e0, {{0x0, 0x18b4a2935c8, 0xfd, 0x0, 0x0, 0x0}, {0x0, 0x18b4a34b0ea, 0xfd, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/insert.go:44 +0x345
github.com/rdleal/intervalst/interval.insert[...](0xc441cf9720, {{0x0, 0x18b4a2935c8, 0xfd, 0x0, 0x0, 0x0}, {0x0, 0x18b4a34b0ea, 0xfd, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/insert.go:108 +0x405
github.com/rdleal/intervalst/interval.(*MultiValueSearchTree[...]).Insert(0x2af53e0, {0x0, 0x18b4a2935c8, 0xfd, 0x0, 0x0, 0x0}, {0x0, 0x18b4a34b0ea, 0xfd, ...}, ...)
	/home/runner/go/pkg/mod/github.com/rdleal/intervalst@v1.2.0/interval/insert.go:91 +0x1d8
	```

**Comment by thorfour** [comment]
I opened a PR for what I believe addresses this. https://github.com/rdleal/intervalst/pull/4 Please let me know if this is not fix you want.

**Comment by rdleal** [comment]
This is totally a bug, I missed those locks. Thanks for reporting and filling a PR with a possible fix. I will review the PR asap.

**Comment by rdleal** [comment]
@thorfour new tag released with you fix.
```sh
go get github.com/rdleal/intervalst@v1.2.1
```

Again, thanks for reporting and collaborating with a fix!
